ext, Color);
    XDrawPoint(Disp, Win, GContext, X, Y);
}

void TXWin::DrawLine(int X1, int Y1, int X2, int Y2, DWORD Color)
{
    XSetForeground(Disp, GContext, Color);
    XDrawLine(Disp, Win, GContex